WITH P AS (
    SELECT
        ID,
        (RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(*) FROM ECOLI_DATA) * 100) AS PERCENT
    FROM ECOLI_DATA
)

SELECT ID,
    CASE
        WHEN PERCENT <= 25 THEN 'CRITICAL'
        WHEN PERCENT <= 50 THEN 'HIGH'
        WHEN PERCENT <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM P
ORDER BY ID