SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN
    FOOD_ORDER O
ON
    P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE <= '2022-05-31'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID