SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN

(SELECT IT.ITEM_ID
FROM ITEM_INFO INF
JOIN ITEM_TREE IT
ON INF.ITEM_ID = IT.PARENT_ITEM_ID
WHERE INF.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC
