SELECT P.CATEGORY, HIGHEST.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN
(
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
) HIGHEST
ON P.CATEGORY = HIGHEST.CATEGORY AND P.PRICE = HIGHEST.MAX_PRICE
ORDER BY P.PRICE DESC